# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d89cb24ca2a7bba4d5a2abc98b18941b583d3778dc3c6d6a4a3fe9b5b39ccd34fe9c1c7f99725c6880f6c109e82a8f89b2f613bcd8cb630d45edc6f6c7233c9b

test:
  secret_key_base: 42e1ceeff1eb2ff34447ac468cf3113e90a77da95d68286665990bc5ee09443082901d9425fdc8a6b6e44d4c8fdc06a3db3b029d5d5cafcce97abceb78781c06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
